name: NSCTabCompleter
version: 2.2.2
author: Nikolai
main: com.nikolai.nsctabcompleter.Main
api-version: 1.13

commands:
  nsctabcompleter:

permissions:
  nsctab.reload:
    default: op
  nsctab.update:
    default: op
  nsctab.bypass.commands.tabcomplation:
    default: false
  nsctab.include.commands.tabcomplation:
    default: false
  nsctab.bypass.commands.execution:
    default: false
  nsctab.include.commands.execution:
    default: false