name: Notify Discord of Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"<@&1391832379932545145>\",
            \"username\": \"NSC Commit Bot\",
            \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\",
            \"embeds\": [{
              \"author\": {
                \"name\": \"${{ github.actor }}\",
                \"url\": \"https://github.com/${{ github.actor }}\",
                \"icon_url\": \"https://github.com/${{ github.actor }}.png\"
              },
              \"title\": \" [${{ github.repository }}](https://github.com/${{ github.repository }}) New Commit ${GITHUB_SHA::7} ${{ github.event.head_commit.message }}\",
              \"description\": \"${{ github.event.head_commit.description }} [here](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\",
              \"url\": \"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\",
              \"color\": 3447003,
              \"footer\": {
                \"text\": \"Pushed to branch: main\"
              },
              \"timestamp\": \"${{ github.event.head_commit.timestamp }}\"
            }]
          }" \
          $DISCORD_WEBHOOK
