name: GitHub Telegram Notify
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Telegram Notify
        uses: EverythingSuckz/github-telegram-notify@v1.1.2
        with:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
          topic_id: ${{ secrets.TOPIC_ID }}
